site_name: MkDoxy
site_url: https://jakubandrysek.github.io/MkDoxy/
site_author: Jakub Andrýsek
site_description: >-
  MkDoxy -> MkDocs + Doxygen. Easy documentation generator with code snippets.

# Repository
repo_name: JakubAndrysek/MkDoxy/
repo_url: https://github.com/JakubAndrysek/MkDoxy/

# Copyright
copyright: Copyright © 2023 Jakub Andrýsek

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: slate
      primary: orange
      accent: orange

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JakubAndrysek
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KubaAndrysek
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakub-andrysek/
#    analytics:
#        provider: google
#        property: G-XXXXXXXXXX

use_directory_urls: True
#use_directory_urls: False

plugins:
  - mkdoxy:
      projects:
        mkdoxyApi:
          src-dirs: mkdoxy
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "*.py"
            EXAMPLE_PATH: ""
            RECURSIVE: True
            OPTIMIZE_OUTPUT_JAVA: True
            JAVADOC_AUTOBRIEF: True
            EXTRACT_ALL: True
      save-api: .mkdoxy
      full-doc: True
      debug: False
      ignore-errors: False


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
  - assets/js/open_in_new_tab.js

nav:
  - Home: 'README.md'
  - MkDocs API:
      - mkdoxyApi/index.md
      - 'Links': 'mkdoxyApi/links.md'
      - 'Classes':
          - 'Class List': 'mkdoxyApi/annotated.md'
          - 'Class Index': 'mkdoxyApi/classes.md'
          - 'Class Hierarchy': 'mkdoxyApi/hierarchy.md'
          - 'Class Members': 'mkdoxyApi/class_members.md'
          - 'Class Member Functions': 'mkdoxyApi/class_member_functions.md'
          - 'Class Member Variables': 'mkdoxyApi/class_member_variables.md'
          - 'Class Member Typedefs': 'mkdoxyApi/class_member_typedefs.md'
          - 'Class Member Enumerations': 'mkdoxyApi/class_member_enums.md'
      - 'Namespaces':
          - 'Namespace List': 'mkdoxyApi/namespaces.md'
          - 'Namespace Members': 'mkdoxyApi/namespace_members.md'
          - 'Namespace Member Functions': 'mkdoxyApi/namespace_member_functions.md'
          - 'Namespace Member Variables': 'mkdoxyApi/namespace_member_variables.md'
          - 'Namespace Member Typedefs': 'mkdoxyApi/namespace_member_typedefs.md'
          - 'Namespace Member Enumerations': 'mkdoxyApi/namespace_member_enums.md'
      - 'Functions': 'mkdoxyApi/functions.md'
      - 'Variables': 'mkdoxyApi/variables.md'
      - 'Macros': 'mkdoxyApi/macros.md'
      - 'Files': 'mkdoxyApi/files.md'