site_name: MkDoxy
site_url: https://mkdoxy.kubaandrysek.cz/
site_author: Jakub Andrýsek
site_description: >-
  MkDoxy -> MkDocs + Doxygen. Easy documentation generator with code snippets.

# Repository
repo_name: JakubAndrysek/MkDoxy/
repo_url: https://github.com/JakubAndrysek/MkDoxy/

# Copyright
copyright: Copyright © 2023 Jakub Andrýsek

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: slate
      primary: orange
      accent: orange

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JakubAndrysek
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/KubaAndrysek
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakub-andrysek/
  analytics:
    provider: google
    property: G-8WHJ2N4SHC
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!

use_directory_urls: True
#use_directory_urls: False

plugins:
  - search
  - open-in-new-tab
  - mkdoxy:
      enabled: !ENV [ENABLE_MKDOXY, True]
      projects:
        mkdoxyApi:
          src-dirs: mkdoxy
          full-doc: True
          # template-dir: templates-custom
          doxy-cfg:
            FILE_PATTERNS: "*.py"
            EXAMPLE_PATH: ""
            RECURSIVE: True
            OPTIMIZE_OUTPUT_JAVA: True
            JAVADOC_AUTOBRIEF: True
            EXTRACT_ALL: True
      save-api: .mkdoxy
      full-doc: True
      debug: False
      ignore-errors: False
      emojis-enabled: True

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - def_list
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.md_in_html
  - pymdownx.blocks.admonition:
      types:
        - new
        - settings
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.details:
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
  - pymdownx.tabbed:
      alternate_style: true


nav:
  - Home: "README.md"
  - Snippets: "mkdoxyApi/snippets.md"
  - MkDocs API:
      - mkdoxyApi/index.md
      - "Links": "mkdoxyApi/links.md"
      - "Classes":
          - "Class List": "mkdoxyApi/annotated.md"
          - "Class Index": "mkdoxyApi/classes.md"
          - "Class Hierarchy": "mkdoxyApi/hierarchy.md"
          - "Class Members": "mkdoxyApi/class_members.md"
          - "Class Member Functions": "mkdoxyApi/class_member_functions.md"
          - "Class Member Variables": "mkdoxyApi/class_member_variables.md"
          - "Class Member Typedefs": "mkdoxyApi/class_member_typedefs.md"
          - "Class Member Enumerations": "mkdoxyApi/class_member_enums.md"
      - "Namespaces":
          - "Namespace List": "mkdoxyApi/namespaces.md"
          - "Namespace Members": "mkdoxyApi/namespace_members.md"
          - "Namespace Member Functions": "mkdoxyApi/namespace_member_functions.md"
          - "Namespace Member Variables": "mkdoxyApi/namespace_member_variables.md"
          - "Namespace Member Typedefs": "mkdoxyApi/namespace_member_typedefs.md"
          - "Namespace Member Enumerations": "mkdoxyApi/namespace_member_enums.md"
      - "Functions": "mkdoxyApi/functions.md"
      - "Variables": "mkdoxyApi/variables.md"
      - "Macros": "mkdoxyApi/macros.md"
      - "Files": "mkdoxyApi/files.md"
