name: MkDoxy test build demos with all supported python versions

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # windows-latest, macos-latest requires doxygen to be installed manually

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[dev]"
          sudo apt-get install doxygen
      - name: Clone test repo
        run: |
          git clone https://github.com/JakubAndrysek/MkDoxy-demo.git demo
      - name: Build docs
        run: |
          cd demo
          git checkout core-update
          python -m pip install -r requirements.txt
          mkdocs build --clean --verbose
